version: '3.8'

services:
  armpi_fpv:
    build: .
    container_name: armpi_fpv
    hostname: armpi_fpv
    
    # Network configuration
    network_mode: host
    
    # Environment variables
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    
    # Volume mounts
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - ./armpi_fpv:/home/ubuntu/armpi_fpv
      - ./course:/home/ubuntu/course
      - ./software:/home/ubuntu/software
      - ./docker_src:/home/ubuntu/docker_src
    
    # Device access
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    
    # Privileges for hardware access
    privileged: true
    
    # Keep container running
    stdin_open: true
    tty: true
    
    # Command to run
    command: /bin/zsh
